name: Lua lint

on: 
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'
      - 'support/**'
      - 'update/**'
  pull_request:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'
      - 'support/**'
      - 'update/**'
    paths:
      - 'src/**'
      - 'bin/**'
      - '**/*.rockspec'
  workflow_dispatch:

env:
  FILES_TO_CHECK: >-
    .
  LUACHECK_CONFIG: .luacheckrc
  LUA_VERSION: "5.4"
  LUAROCKS_VERSION: "3.8.0"
  WORKFLOW_REPO: Warhammer-Mods/workflows
  WORKFLOW_REPO_REF: v1

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: ${{ env.LUA_VERSION }}
        
    - uses: leafo/gh-actions-luarocks@v4.1.0
      with:
        luarocksVersion: ${{ env.LUAROCKS_VERSION }}
        
    - name: Install luacheck
      run: luarocks install luacheck

    - name: Luacheck Lint
      id: luacheck
      shell: bash --noprofile --norc {0}
      env:
        matcher: luacheck-plain.json
      run: |
        curl -sL --fail \
          -o ${matcher} \
          "${GITHUB_SERVER_URL}/${{ env.WORKFLOW_REPO }}/raw/${{ env.WORKFLOW_REPO_REF }}/.github/${matcher}"

        echo "::add-matcher::${matcher}"
        luacheck ${{ env.FILES_TO_CHECK }} \
          --formatter plain \
          --codes --ranges \
          --config ${{ env.LUACHECK_CONFIG }}
        exitcode=$?
        echo "::remove-matcher owner=luacheck-plain_error::"
        echo "::remove-matcher owner=luacheck-plain_warning::"
        if [ "$exitcode" -gt 1 ]; then
          exit $exitcode;
        else
          exit 0;
        fi
